services:
  gophermart:
    build: .
    container_name: gophermart
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - app_network
  db:
    image: postgres:17.2
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      timeout: 3s


networks:
  app_network:
    driver: bridge
