name: Lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64
          args: --config=.golangci.yml
